using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;

namespace Content.Client._Funkystation.Payouts;

[GenerateTypedNameReferences]
public sealed partial class PayoutsConsoleWindow : FancyWindow
{

}
